### ISSUE TITLE
Large bundle size because all font-awesome icons are included 

### ISSUE THREAD

**Issue by MrToph** [EOSIO/ual-reactjs-renderer#103]
Hi, I noticed a huge bundle size for all projects using `ual-reactjs-renderer`. 
[Bundlephobia](https://bundlephobia.com/result?p=ual-reactjs-renderer@0.3.1) reports the same - 2MB **minified**.

After some investigation, the issue seems to be the usage of react-icons which includes all SVGs.

![image](https://user-images.githubusercontent.com/3176721/98593232-23437780-22d3-11eb-97a9-774095c3b7df.png)

**Comment by MrToph** [comment]
Fixed this in #104 and published a temporary (?) package under [@cmichel/ual-reactjs-renderer](https://bundlephobia.com/result?p=@cmichel/ual-reactjs-renderer@0.4.0).

There should be a solution using webpack or rollup instead of transpiling with babel but I couldn't make it work.
If the changes or another fix is merged upstream, I'll deprecate my package.

**Comment by Fabioepb** [comment]
How is this not fixed over a year later?

The build size of the project I'm working on tripled just by including this library..

**Comment by Fabioepb** [comment]
@josephjguerra
